version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "img-clf"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ph3mf5q4s8ba"
s3_prefix = "img-clf"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["InferenceFunction=454445151329.dkr.ecr.us-east-1.amazonaws.com/imgclfe5e82746/inferencefunction7c73919drepo"]
parameter_overrides = "EFSpath=\"/mnt/ml\" SecurityGroupIds=\"sg-03e2e196ada48301b\" SubnetIDs=\"subnet-009ffc4b5c829c879, subnet-05c100c9fc1f3832b, subnet-0c9ae51cce9e20f8f, subnet-052824890995c9ada, subnet-00fc708ddfba07930, subnet-00c03a67cd669e651\" AccessPointARN=\"arn:aws:elasticfilesystem:us-east-1:454445151329:access-point/fsap-048395683297eca23\""
